version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - errorlint
    - misspell
    - revive
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    staticcheck:
      checks: ["all"]
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - gosec
        text: "G404"
